# coding: utf-8

"""
    BoltStoresAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class CreateTileLayoutValue(BaseModel):
    """
    CreateTileLayoutValue
    """ # noqa: E501
    title: Dict[str, StrictStr] = Field(description="A dictionary that contains translations to several languages.  Keys are locales (\"en-US\", \"ro-RO\", etc.), values are translations.  Example: `{ \"en-US\": \"Milk\", \"ee-EE\": \"Piim\" }` ")
    position: StrictInt = Field(description="Position of the section within the layout, represented as an integer from 0 to 999 indicating its display order.")
    description: Optional[Dict[str, StrictStr]] = Field(default=None, description="A dictionary that contains translations to several languages.  Keys are locales (\"en-US\", \"ro-RO\", etc.), values are translations.  Example: `{ \"en-US\": \"Milk\", \"ee-EE\": \"Piim\" }` ")
    tile_bg_color_light: Optional[StrictStr] = Field(default=None, description="Background color of the section tile in light mode. It is a string that represents the color in hex format. Expected format: #RRGGBBAA.")
    tile_bg_color_dark: Optional[StrictStr] = Field(default=None, description="Background color of the section tile in dark mode. It is a string that represents the color in hex format. Expected format: #RRGGBBAA.")
    __properties: ClassVar[List[str]] = ["title", "position", "description", "tile_bg_color_light", "tile_bg_color_dark"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateTileLayoutValue from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateTileLayoutValue from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "title": obj.get("title"),
            "position": obj.get("position"),
            "description": obj.get("description"),
            "tile_bg_color_light": obj.get("tile_bg_color_light"),
            "tile_bg_color_dark": obj.get("tile_bg_color_dark")
        })
        return _obj


