# coding: utf-8

"""
    BoltStoresAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class Fee(BaseModel):
    """
    Fee
    """ # noqa: E501
    id: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="A numeric identifier of a fee")
    sku: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=255)]] = Field(default=None, description="A unique string identifier of a product (stands for a “Stock Keeping Unit”) ")
    name: Optional[Dict[str, StrictStr]] = Field(default=None, description="A dictionary that contains translations to several languages.  Keys are locales (\"en-US\", \"ro-RO\", etc.), values are translations.  Example: `{ \"en-US\": \"Milk\", \"ee-EE\": \"Piim\" }` ")
    description: Optional[Dict[str, StrictStr]] = Field(default=None, description="A dictionary that contains translations to several languages.  Keys are locales (\"en-US\", \"ro-RO\", etc.), values are translations.  Example: `{ \"en-US\": \"Milk\", \"ee-EE\": \"Piim\" }` ")
    price: Optional[Union[Annotated[float, Field(strict=True, ge=0.00010)], Annotated[int, Field(strict=True, ge=1)]]] = Field(default=None, description="A price for the SKU with four-digit precision")
    type: Optional[StrictStr] = Field(default=None, description="The type of fee")
    __properties: ClassVar[List[str]] = ["id", "sku", "name", "description", "price", "type"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['deposit', 'sup_cup', 'sup_container']):
            raise ValueError("must be one of enum values ('deposit', 'sup_cup', 'sup_container')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Fee from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Fee from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "sku": obj.get("sku"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "price": obj.get("price"),
            "type": obj.get("type")
        })
        return _obj


