# coding: utf-8

"""
    BoltStoresAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from openapi_client.models.generic_pos_api_price import GenericPosApiPrice
from openapi_client.models.generic_pos_option import GenericPosOption
from openapi_client.models.measure_with_total import MeasureWithTotal
from typing import Optional, Set
from typing_extensions import Self

class GenericPosItem(BaseModel):
    """
    GenericPosItem object that represents an item
    """ # noqa: E501
    name: Optional[StrictStr] = Field(default=None, description="The item's name")
    sku: Optional[StrictStr] = Field(default=None, description="A unique string corresponding to a specific product (SKU). Min length: 1, max length: 255")
    qty: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The items's amount")
    unit_item_price: Optional[GenericPosApiPrice] = None
    options: Optional[List[GenericPosOption]] = None
    total_item_price: Optional[GenericPosApiPrice] = None
    user_note: Optional[StrictStr] = Field(default=None, description="The user note for this item.")
    measure: Optional[MeasureWithTotal] = None
    __properties: ClassVar[List[str]] = ["name", "sku", "qty", "unit_item_price", "options", "total_item_price", "user_note", "measure"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GenericPosItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of unit_item_price
        if self.unit_item_price:
            _dict['unit_item_price'] = self.unit_item_price.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in options (list)
        _items = []
        if self.options:
            for _item_options in self.options:
                if _item_options:
                    _items.append(_item_options.to_dict())
            _dict['options'] = _items
        # override the default output from pydantic by calling `to_dict()` of total_item_price
        if self.total_item_price:
            _dict['total_item_price'] = self.total_item_price.to_dict()
        # override the default output from pydantic by calling `to_dict()` of measure
        if self.measure:
            _dict['measure'] = self.measure.to_dict()
        # set to None if sku (nullable) is None
        # and model_fields_set contains the field
        if self.sku is None and "sku" in self.model_fields_set:
            _dict['sku'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GenericPosItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "sku": obj.get("sku"),
            "qty": obj.get("qty"),
            "unit_item_price": GenericPosApiPrice.from_dict(obj["unit_item_price"]) if obj.get("unit_item_price") is not None else None,
            "options": [GenericPosOption.from_dict(_item) for _item in obj["options"]] if obj.get("options") is not None else None,
            "total_item_price": GenericPosApiPrice.from_dict(obj["total_item_price"]) if obj.get("total_item_price") is not None else None,
            "user_note": obj.get("user_note"),
            "measure": MeasureWithTotal.from_dict(obj["measure"]) if obj.get("measure") is not None else None
        })
        return _obj


