# coding: utf-8

"""
    BoltStoresAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class GenericPosOption(BaseModel):
    """
    GenericPosOption object that represents the option of an item
    """ # noqa: E501
    name: Optional[StrictStr] = Field(default=None, description="The option's name")
    sku: Optional[StrictStr] = Field(default=None, description="A unique string corresponding to a specific product (SKU). Min length: 1, max length: 255")
    qty: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The option's amount")
    unit_item_price: Optional[Any] = None
    total_item_price: Optional[Any] = None
    __properties: ClassVar[List[str]] = ["name", "sku", "qty", "unit_item_price", "total_item_price"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GenericPosOption from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if sku (nullable) is None
        # and model_fields_set contains the field
        if self.sku is None and "sku" in self.model_fields_set:
            _dict['sku'] = None

        # set to None if unit_item_price (nullable) is None
        # and model_fields_set contains the field
        if self.unit_item_price is None and "unit_item_price" in self.model_fields_set:
            _dict['unit_item_price'] = None

        # set to None if total_item_price (nullable) is None
        # and model_fields_set contains the field
        if self.total_item_price is None and "total_item_price" in self.model_fields_set:
            _dict['total_item_price'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GenericPosOption from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "sku": obj.get("sku"),
            "qty": obj.get("qty"),
            "unit_item_price": obj.get("unit_item_price"),
            "total_item_price": obj.get("total_item_price")
        })
        return _obj


