# coding: utf-8

"""
    BoltStoresAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class PickedItemPrice(BaseModel):
    """
    Price of an order item
    """ # noqa: E501
    currency: Annotated[str, Field(min_length=3, strict=True, max_length=3)] = Field(description="The ISO 4217 code of a currency")
    includes_bottle_deposit: Optional[StrictBool] = Field(default=None, description="Accepts false only. Currently we expect all prices not to include Bottle Deposits")
    original_value: Optional[Union[Annotated[float, Field(strict=True, ge=0.00010)], Annotated[int, Field(strict=True, ge=1)]]] = Field(default=None, description="The value to which the change was made with four-digit precision. Used for tracking purposes")
    price_change_reasons: Optional[List[StrictStr]] = Field(default=None, description="The reason(s) why the price has been changed")
    value: Union[Annotated[float, Field(strict=True, ge=0.00010)], Annotated[int, Field(strict=True, ge=1)]] = Field(description="Floating point price of an SKU")
    __properties: ClassVar[List[str]] = ["currency", "includes_bottle_deposit", "original_value", "price_change_reasons", "value"]

    @field_validator('price_change_reasons')
    def price_change_reasons_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        for i in value:
            if i not in set(['weight', 'loyalty', 'discount', 'price_mismatch']):
                raise ValueError("each list item must be one of ('weight', 'loyalty', 'discount', 'price_mismatch')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PickedItemPrice from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PickedItemPrice from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "currency": obj.get("currency"),
            "includes_bottle_deposit": obj.get("includes_bottle_deposit"),
            "original_value": obj.get("original_value"),
            "price_change_reasons": obj.get("price_change_reasons"),
            "value": obj.get("value")
        })
        return _obj


