# coding: utf-8

"""
    BoltStoresAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.pim_v1_menu_drafts_state_errors_inner import PimV1MenuDraftsStateErrorsInner
from typing import Optional, Set
from typing_extensions import Self

class PimV1MenuDraftsState(BaseModel):
    """
    The state of a menu draft
    """ # noqa: E501
    state: StrictStr
    error_message: Optional[StrictStr] = Field(default=None, description="The general description of an error that occurred while processing the draft, if any ")
    errors: Optional[List[PimV1MenuDraftsStateErrorsInner]] = Field(default=None, description="An array of specific validation errors related to certain SKUs")
    created: Optional[StrictInt] = Field(default=None, description="A UNIX timestamp of the draft creation")
    updated: Optional[StrictInt] = Field(default=None, description="A UNIX timestamp of the latest draft state change")
    __properties: ClassVar[List[str]] = ["state", "error_message", "errors", "created", "updated"]

    @field_validator('state')
    def state_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['no_draft', 'processing', 'failed', 'waiting_for_review']):
            raise ValueError("must be one of enum values ('no_draft', 'processing', 'failed', 'waiting_for_review')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PimV1MenuDraftsState from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in errors (list)
        _items = []
        if self.errors:
            for _item_errors in self.errors:
                if _item_errors:
                    _items.append(_item_errors.to_dict())
            _dict['errors'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PimV1MenuDraftsState from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "state": obj.get("state"),
            "error_message": obj.get("error_message"),
            "errors": [PimV1MenuDraftsStateErrorsInner.from_dict(_item) for _item in obj["errors"]] if obj.get("errors") is not None else None,
            "created": obj.get("created"),
            "updated": obj.get("updated")
        })
        return _obj


