# coding: utf-8

"""
    BoltStoresAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List
from typing_extensions import Annotated
from openapi_client.models.post_pim_v1_product_prices_import_request_price_list_skus_inner import PostPimV1ProductPricesImportRequestPriceListSkusInner
from typing import Optional, Set
from typing_extensions import Self

class PostPimV1ProductPricesImportRequestPriceList(BaseModel):
    """
    PostPimV1ProductPricesImportRequestPriceList
    """ # noqa: E501
    currency: Annotated[str, Field(min_length=3, strict=True, max_length=3)] = Field(description="The ISO 4217 code of a currency")
    skus: Annotated[List[PostPimV1ProductPricesImportRequestPriceListSkusInner], Field(max_length=20000)]
    __properties: ClassVar[List[str]] = ["currency", "skus"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PostPimV1ProductPricesImportRequestPriceList from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in skus (list)
        _items = []
        if self.skus:
            for _item_skus in self.skus:
                if _item_skus:
                    _items.append(_item_skus.to_dict())
            _dict['skus'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PostPimV1ProductPricesImportRequestPriceList from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "currency": obj.get("currency"),
            "skus": [PostPimV1ProductPricesImportRequestPriceListSkusInner.from_dict(_item) for _item in obj["skus"]] if obj.get("skus") is not None else None
        })
        return _obj


