# coding: utf-8

"""
    BoltStoresAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from openapi_client.models.post_pim_v1_products_discount_prices_import_request_discount_price_list_inner import PostPimV1ProductsDiscountPricesImportRequestDiscountPriceListInner
from typing import Optional, Set
from typing_extensions import Self

class PostPimV1ProductsDiscountPricesImportRequest(BaseModel):
    """
    PostPimV1ProductsDiscountPricesImportRequest
    """ # noqa: E501
    region_id: StrictInt = Field(description="An identifier of the region that the operation applies to. Consult technical support or the PIM Web interface to retrieve this id ")
    provider_ids: Optional[List[StrictStr]] = Field(default=None, description="An array of provider ids the price applies to.   If not set, the prices will be overwritten for all providers in the region. ")
    currency: Annotated[str, Field(min_length=3, strict=True, max_length=3)] = Field(description="The ISO 4217 code of a currency")
    discount_price_list: List[PostPimV1ProductsDiscountPricesImportRequestDiscountPriceListInner]
    __properties: ClassVar[List[str]] = ["region_id", "provider_ids", "currency", "discount_price_list"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PostPimV1ProductsDiscountPricesImportRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in discount_price_list (list)
        _items = []
        if self.discount_price_list:
            for _item_discount_price_list in self.discount_price_list:
                if _item_discount_price_list:
                    _items.append(_item_discount_price_list.to_dict())
            _dict['discount_price_list'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PostPimV1ProductsDiscountPricesImportRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "region_id": obj.get("region_id"),
            "provider_ids": obj.get("provider_ids"),
            "currency": obj.get("currency"),
            "discount_price_list": [PostPimV1ProductsDiscountPricesImportRequestDiscountPriceListInner.from_dict(_item) for _item in obj["discount_price_list"]] if obj.get("discount_price_list") is not None else None
        })
        return _obj


