# coding: utf-8

"""
    BoltStoresAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.post_v2mark_order_with_items_as_ready_for_pick_up_request_items_inner import PostV2markOrderWithItemsAsReadyForPickUpRequestItemsInner
from typing import Optional, Set
from typing_extensions import Self

class PostV2markOrderWithItemsAsReadyForPickUpRequest(BaseModel):
    """
    PostV2markOrderWithItemsAsReadyForPickUpRequest
    """ # noqa: E501
    provider_id: StrictStr = Field(description="A unique string identifier of the provider  (contact Bolt Food support to obtain one) ")
    order_id: StrictInt = Field(description="A numeric identifier of an order, provided by Bolt Food")
    replacement_mode: Optional[StrictStr] = Field(default=None, description="A replacement mode that identifies how replacements should be handled: manually or automatically.  If `strict` is chosen, all replacement information should be provided in the `replacement_for` field in the item; nothing will be calculated additionally. All items initially not in the order and not marked as replacements will be assumed to be free.  If `heuristic` is chosen, all `replacement_for` field information will be ignored, and replacements will be assumed based on provided item quantities and prices. ")
    items: List[PostV2markOrderWithItemsAsReadyForPickUpRequestItemsInner] = Field(description="An array of SKU amounts and prices collected.")
    __properties: ClassVar[List[str]] = ["provider_id", "order_id", "replacement_mode", "items"]

    @field_validator('replacement_mode')
    def replacement_mode_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['strict', 'heuristic']):
            raise ValueError("must be one of enum values ('strict', 'heuristic')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PostV2markOrderWithItemsAsReadyForPickUpRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in items (list)
        _items = []
        if self.items:
            for _item_items in self.items:
                if _item_items:
                    _items.append(_item_items.to_dict())
            _dict['items'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PostV2markOrderWithItemsAsReadyForPickUpRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "provider_id": obj.get("provider_id"),
            "order_id": obj.get("order_id"),
            "replacement_mode": obj.get("replacement_mode"),
            "items": [PostV2markOrderWithItemsAsReadyForPickUpRequestItemsInner.from_dict(_item) for _item in obj["items"]] if obj.get("items") is not None else None
        })
        return _obj


