# coding: utf-8

"""
    BoltStoresAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from openapi_client.models.measure_info import MeasureInfo
from typing import Optional, Set
from typing_extensions import Self

class ReplacementInfo(BaseModel):
    """
    Information about the product that was replaced.
    """ # noqa: E501
    replaced_sku: Annotated[str, Field(min_length=1, strict=True, max_length=255)] = Field(description="A unique string identifier of a product (stands for a “Stock Keeping Unit”) ")
    replaced_quantity: StrictInt = Field(description="Amount of the product that was replaced. ")
    replaced_measure_info: Optional[MeasureInfo] = Field(default=None, description="Measure information of the product that was replaced. ")
    picked_quantity: StrictInt = Field(description="Amount of the product that was used for replacement. ")
    picked_measure_info: Optional[MeasureInfo] = Field(default=None, description="Measure information of the product that was used for replacement. ")
    __properties: ClassVar[List[str]] = ["replaced_sku", "replaced_quantity", "replaced_measure_info", "picked_quantity", "picked_measure_info"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ReplacementInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of replaced_measure_info
        if self.replaced_measure_info:
            _dict['replaced_measure_info'] = self.replaced_measure_info.to_dict()
        # override the default output from pydantic by calling `to_dict()` of picked_measure_info
        if self.picked_measure_info:
            _dict['picked_measure_info'] = self.picked_measure_info.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ReplacementInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "replaced_sku": obj.get("replaced_sku"),
            "replaced_quantity": obj.get("replaced_quantity"),
            "replaced_measure_info": MeasureInfo.from_dict(obj["replaced_measure_info"]) if obj.get("replaced_measure_info") is not None else None,
            "picked_quantity": obj.get("picked_quantity"),
            "picked_measure_info": MeasureInfo.from_dict(obj["picked_measure_info"]) if obj.get("picked_measure_info") is not None else None
        })
        return _obj


