# coding: utf-8

"""
    BoltStoresAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt
from typing import Any, ClassVar, Dict, List
from typing_extensions import Annotated
from openapi_client.models.weekdays_availability import WeekdaysAvailability
from typing import Optional, Set
from typing_extensions import Self

class Timetable(BaseModel):
    """
    Timetable
    """ # noqa: E501
    id: StrictInt = Field(description="An id of a timetable")
    region_id: StrictInt = Field(description="An id of the region the timetable is bound to")
    name: Annotated[str, Field(min_length=1, strict=True, max_length=255)] = Field(description="Timetable name")
    availabilities: WeekdaysAvailability
    is_active: StrictBool = Field(description="Is timetable active")
    __properties: ClassVar[List[str]] = ["id", "region_id", "name", "availabilities", "is_active"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Timetable from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of availabilities
        if self.availabilities:
            _dict['availabilities'] = self.availabilities.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Timetable from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "region_id": obj.get("region_id"),
            "name": obj.get("name"),
            "availabilities": WeekdaysAvailability.from_dict(obj["availabilities"]) if obj.get("availabilities") is not None else None,
            "is_active": obj.get("is_active")
        })
        return _obj


