# coding: utf-8

"""
    BoltFoodAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from openapi_client.models.option_group_type import OptionGroupType
from typing import Optional, Set
from typing_extensions import Self

class ExternalOptionGroupRequest(BaseModel):
    """
    ExternalOptionGroupRequest
    """ # noqa: E501
    external_id: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=255)]] = Field(default=None, description="An external identifier of an option group")
    title: Dict[str, StrictStr] = Field(description="A dictionary that contains translations to several languages.  Keys are locales (\"en-US\", \"ro-RO\", etc.), values are translations.  Example: `{ \"en-US\": \"Milk\", \"ee-EE\": \"Piim\" }` ")
    type: OptionGroupType
    min_quantity: Annotated[int, Field(strict=True, ge=0)]
    max_quantity: Annotated[int, Field(strict=True, ge=1)]
    max_quantity_each: Annotated[int, Field(strict=True, ge=1)]
    is_required: StrictBool
    option_skus: List[Annotated[str, Field(min_length=1, strict=True, max_length=255)]]
    __properties: ClassVar[List[str]] = ["external_id", "title", "type", "min_quantity", "max_quantity", "max_quantity_each", "is_required", "option_skus"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ExternalOptionGroupRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ExternalOptionGroupRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "external_id": obj.get("external_id"),
            "title": obj.get("title"),
            "type": obj.get("type"),
            "min_quantity": obj.get("min_quantity"),
            "max_quantity": obj.get("max_quantity"),
            "max_quantity_each": obj.get("max_quantity_each"),
            "is_required": obj.get("is_required"),
            "option_skus": obj.get("option_skus")
        })
        return _obj


