# coding: utf-8

"""
    BoltFoodAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class MeasureWithTotal(BaseModel):
    """
    For products sold by measurement (e.g., by weight), this contains:<br>   * The measurement unit<br>   * he measured quantity (i.e., the weight or volume) one \"piece\" of the product contains<br>   * The total measure (e.g., weight) ordered by the customer<br>  For example, if the customer ordered 2 zucchinis and the expected weight of each zucchini is 1.5 kg, the payload will contain:<br> {<br>     \"unit\": \"gram\",<br>     \"piece_measured_quantity\": 1500,<br>     \"total_measured_quantity\": 3000<br> }
    """ # noqa: E501
    total_measured_quantity: Optional[Union[StrictFloat, StrictInt]] = None
    unit: Optional[StrictStr] = None
    piece_measured_quantity: Optional[Union[StrictFloat, StrictInt]] = None
    __properties: ClassVar[List[str]] = ["total_measured_quantity", "unit", "piece_measured_quantity"]

    @field_validator('unit')
    def unit_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['piece', 'gram', 'milliliter']):
            raise ValueError("must be one of enum values ('piece', 'gram', 'milliliter')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MeasureWithTotal from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MeasureWithTotal from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "total_measured_quantity": obj.get("total_measured_quantity"),
            "unit": obj.get("unit"),
            "piece_measured_quantity": obj.get("piece_measured_quantity")
        })
        return _obj


