# coding: utf-8

"""
    BoltFoodAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.generic_append_existing_order import GenericAppendExistingOrder
from openapi_client.models.generic_create_order_item import GenericCreateOrderItem
from typing import Optional, Set
from typing_extensions import Self

class PostWaiterCreateOrderRequest(BaseModel):
    """
    PostWaiterCreateOrderRequest
    """ # noqa: E501
    provider_id: StrictStr = Field(description="A unique string identifier of the provider  (contact Bolt Food support to obtain one) ")
    table: StrictStr = Field(description="The table number for the order.")
    order_items: List[GenericCreateOrderItem] = Field(description="Array of `GenericCreateOrderItem` objects. The `GenericCreateOrderItem` object consists of the details needed for an item that will be present in the order.")
    append_to_existing_order: Optional[GenericAppendExistingOrder] = Field(default=None, description="Used to append the items in this payload to an existing order. <br> Thus, this newly added items will create a new Item Group for the existing mentioned order. <br> Do not use this field when trying to create an order from scratch <br>")
    __properties: ClassVar[List[str]] = ["provider_id", "table", "order_items", "append_to_existing_order"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PostWaiterCreateOrderRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in order_items (list)
        _items = []
        if self.order_items:
            for _item_order_items in self.order_items:
                if _item_order_items:
                    _items.append(_item_order_items.to_dict())
            _dict['order_items'] = _items
        # override the default output from pydantic by calling `to_dict()` of append_to_existing_order
        if self.append_to_existing_order:
            _dict['append_to_existing_order'] = self.append_to_existing_order.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PostWaiterCreateOrderRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "provider_id": obj.get("provider_id"),
            "table": obj.get("table"),
            "order_items": [GenericCreateOrderItem.from_dict(_item) for _item in obj["order_items"]] if obj.get("order_items") is not None else None,
            "append_to_existing_order": GenericAppendExistingOrder.from_dict(obj["append_to_existing_order"]) if obj.get("append_to_existing_order") is not None else None
        })
        return _obj


