# coding: utf-8

"""
    BoltFoodAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.post_update_menu_item_availability_request_menu_item_availability_updates_inner import PostUpdateMenuItemAvailabilityRequestMenuItemAvailabilityUpdatesInner
from typing import Optional, Set
from typing_extensions import Self

class PostUpdateMenuItemAvailabilityRequest(BaseModel):
    """
    PostUpdateMenuItemAvailabilityRequest
    """ # noqa: E501
    provider_id: StrictStr = Field(description="Unique value for provider (given by Bolt Food)")
    menu_item_availability_updates: List[PostUpdateMenuItemAvailabilityRequestMenuItemAvailabilityUpdatesInner] = Field(description="list of menu item availability transitions")
    : Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["provider_id", "menu_item_availability_updates", ""]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PostUpdateMenuItemAvailabilityRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in menu_item_availability_updates (list)
        _items = []
        if self.menu_item_availability_updates:
            for _item_menu_item_availability_updates in self.menu_item_availability_updates:
                if _item_menu_item_availability_updates:
                    _items.append(_item_menu_item_availability_updates.to_dict())
            _dict['menu_item_availability_updates'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PostUpdateMenuItemAvailabilityRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "provider_id": obj.get("provider_id"),
            "menu_item_availability_updates": [PostUpdateMenuItemAvailabilityRequestMenuItemAvailabilityUpdatesInner.from_dict(_item) for _item in obj["menu_item_availability_updates"]] if obj.get("menu_item_availability_updates") is not None else None,
            "": obj.get("")
        })
        return _obj


