# coding: utf-8

"""
    BoltFoodAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.generic_menu_item import GenericMenuItem
from typing import Optional, Set
from typing_extensions import Self

class PushMenuRequestBody(BaseModel):
    """
    PushMenuRequestBody
    """ # noqa: E501
    provider_id: Optional[StrictStr] = Field(default=None, description="A unique string identifier of the provider  (contact Bolt Food support to obtain one) ")
    provider_ids: Optional[List[StrictStr]] = Field(default=None, description="Provider ids specified in this field must belong to the same restaurant chain  (vendor entity in Bolt Food terminology) per one city, otherwise a bad request response is returned\" ")
    root_key: StrictStr = Field(description="root_key is the key of the menu item of type menu")
    force_reimport_images: Optional[StrictBool] = Field(default=None, description="Flag which enables reupload of all menu images, for reprocessing")
    menu: Dict[str, GenericMenuItem] = Field(description="Menu structure is like a tree (top node is the menu node), on the next level we have categories. Under menu categories we have dishes. Under dishes we may have option groups. Each option group must have at least one option. ")
    __properties: ClassVar[List[str]] = ["provider_id", "provider_ids", "root_key", "force_reimport_images", "menu"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PushMenuRequestBody from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in menu (dict)
        _field_dict = {}
        if self.menu:
            for _key_menu in self.menu:
                if self.menu[_key_menu]:
                    _field_dict[_key_menu] = self.menu[_key_menu].to_dict()
            _dict['menu'] = _field_dict
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PushMenuRequestBody from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "provider_id": obj.get("provider_id"),
            "provider_ids": obj.get("provider_ids"),
            "root_key": obj.get("root_key"),
            "force_reimport_images": obj.get("force_reimport_images"),
            "menu": dict(
                (_k, GenericMenuItem.from_dict(_v))
                for _k, _v in obj["menu"].items()
            )
            if obj.get("menu") is not None
            else None
        })
        return _obj


