# coding: utf-8

"""
    BoltStoresAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictStr
from typing import Optional
from typing_extensions import Annotated
from openapi_client.models.inline_object1 import InlineObject1
from openapi_client.models.post_pim_v1_category_products_set_request import PostPimV1CategoryProductsSetRequest
from openapi_client.models.post_pim_v1_category_rearrange_request import PostPimV1CategoryRearrangeRequest
from openapi_client.models.post_pim_v1_category_tree_get200_response import PostPimV1CategoryTreeGet200Response
from openapi_client.models.post_pim_v1_category_tree_set_request import PostPimV1CategoryTreeSetRequest
from openapi_client.models.post_pim_v1_products_import_status_retrieve_request import PostPimV1ProductsImportStatusRetrieveRequest

from openapi_client.api_client import ApiClient, RequestSerialized
from openapi_client.api_response import ApiResponse
from openapi_client.rest import RESTResponseType


class PIMIntegrationCategoriesAndOrderingApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def post_pim_v1_category_products_set(
        self,
        x_external_integrator_id: Annotated[StrictStr, Field(description="Integration ID provided by Bolt Food. It will be unique across all providers. ")],
        x_server_authorization_hmac_sha256: Annotated[StrictStr, Field(description="Signature of the raw payload outputted in base64, computed with sha256 algorithm and a secret key that you will receive from Bolt Food. ")],
        post_pim_v1_category_products_set_request: Optional[PostPimV1CategoryProductsSetRequest] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> InlineObject1:
        """Set category products

        Assigns existing products to a category in the same order as `ordered_skus` in the request. _(you can enable this feature by contacting the Bolt Food support)_  If no existing category could be found with the external id provided, a `CATEGORY_NOT_FOUND` (code: 40038) error will be returned and changes will be discarded.  If list of the products in the request: * Contains any products not existing in region, a `PRODUCT_NOT_FOUND` (code: 40018) error will be returned and changes will be discarded. * Contains any duplicated SKUs, a `DUPLICATED_PRODUCTS` (code: 40037) error will be returned and changes will be discarded. * Is missing any products already assigned to this category, they will be unbound/unassigned from the category. * Contains only products already assigned to the category, only the order of the products will be updated.  **NB**. Rearranging the category does not automatically update  the menu in the Bolt Food app. To do so, the menu publishing flow needs to be invoked. See  [Assortment and Menu Publishing Flow](#tag/Doc-Warehouse-and-PIM-integration/Assortment-and-menu-publishing-flow). 

        :param x_external_integrator_id: Integration ID provided by Bolt Food. It will be unique across all providers.  (required)
        :type x_external_integrator_id: str
        :param x_server_authorization_hmac_sha256: Signature of the raw payload outputted in base64, computed with sha256 algorithm and a secret key that you will receive from Bolt Food.  (required)
        :type x_server_authorization_hmac_sha256: str
        :param post_pim_v1_category_products_set_request:
        :type post_pim_v1_category_products_set_request: PostPimV1CategoryProductsSetRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._post_pim_v1_category_products_set_serialize(
            x_external_integrator_id=x_external_integrator_id,
            x_server_authorization_hmac_sha256=x_server_authorization_hmac_sha256,
            post_pim_v1_category_products_set_request=post_pim_v1_category_products_set_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "InlineObject1",
            '400': None,
            '401': None,
            '403': None,
            '429': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def post_pim_v1_category_products_set_with_http_info(
        self,
        x_external_integrator_id: Annotated[StrictStr, Field(description="Integration ID provided by Bolt Food. It will be unique across all providers. ")],
        x_server_authorization_hmac_sha256: Annotated[StrictStr, Field(description="Signature of the raw payload outputted in base64, computed with sha256 algorithm and a secret key that you will receive from Bolt Food. ")],
        post_pim_v1_category_products_set_request: Optional[PostPimV1CategoryProductsSetRequest] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[InlineObject1]:
        """Set category products

        Assigns existing products to a category in the same order as `ordered_skus` in the request. _(you can enable this feature by contacting the Bolt Food support)_  If no existing category could be found with the external id provided, a `CATEGORY_NOT_FOUND` (code: 40038) error will be returned and changes will be discarded.  If list of the products in the request: * Contains any products not existing in region, a `PRODUCT_NOT_FOUND` (code: 40018) error will be returned and changes will be discarded. * Contains any duplicated SKUs, a `DUPLICATED_PRODUCTS` (code: 40037) error will be returned and changes will be discarded. * Is missing any products already assigned to this category, they will be unbound/unassigned from the category. * Contains only products already assigned to the category, only the order of the products will be updated.  **NB**. Rearranging the category does not automatically update  the menu in the Bolt Food app. To do so, the menu publishing flow needs to be invoked. See  [Assortment and Menu Publishing Flow](#tag/Doc-Warehouse-and-PIM-integration/Assortment-and-menu-publishing-flow). 

        :param x_external_integrator_id: Integration ID provided by Bolt Food. It will be unique across all providers.  (required)
        :type x_external_integrator_id: str
        :param x_server_authorization_hmac_sha256: Signature of the raw payload outputted in base64, computed with sha256 algorithm and a secret key that you will receive from Bolt Food.  (required)
        :type x_server_authorization_hmac_sha256: str
        :param post_pim_v1_category_products_set_request:
        :type post_pim_v1_category_products_set_request: PostPimV1CategoryProductsSetRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._post_pim_v1_category_products_set_serialize(
            x_external_integrator_id=x_external_integrator_id,
            x_server_authorization_hmac_sha256=x_server_authorization_hmac_sha256,
            post_pim_v1_category_products_set_request=post_pim_v1_category_products_set_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "InlineObject1",
            '400': None,
            '401': None,
            '403': None,
            '429': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def post_pim_v1_category_products_set_without_preload_content(
        self,
        x_external_integrator_id: Annotated[StrictStr, Field(description="Integration ID provided by Bolt Food. It will be unique across all providers. ")],
        x_server_authorization_hmac_sha256: Annotated[StrictStr, Field(description="Signature of the raw payload outputted in base64, computed with sha256 algorithm and a secret key that you will receive from Bolt Food. ")],
        post_pim_v1_category_products_set_request: Optional[PostPimV1CategoryProductsSetRequest] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Set category products

        Assigns existing products to a category in the same order as `ordered_skus` in the request. _(you can enable this feature by contacting the Bolt Food support)_  If no existing category could be found with the external id provided, a `CATEGORY_NOT_FOUND` (code: 40038) error will be returned and changes will be discarded.  If list of the products in the request: * Contains any products not existing in region, a `PRODUCT_NOT_FOUND` (code: 40018) error will be returned and changes will be discarded. * Contains any duplicated SKUs, a `DUPLICATED_PRODUCTS` (code: 40037) error will be returned and changes will be discarded. * Is missing any products already assigned to this category, they will be unbound/unassigned from the category. * Contains only products already assigned to the category, only the order of the products will be updated.  **NB**. Rearranging the category does not automatically update  the menu in the Bolt Food app. To do so, the menu publishing flow needs to be invoked. See  [Assortment and Menu Publishing Flow](#tag/Doc-Warehouse-and-PIM-integration/Assortment-and-menu-publishing-flow). 

        :param x_external_integrator_id: Integration ID provided by Bolt Food. It will be unique across all providers.  (required)
        :type x_external_integrator_id: str
        :param x_server_authorization_hmac_sha256: Signature of the raw payload outputted in base64, computed with sha256 algorithm and a secret key that you will receive from Bolt Food.  (required)
        :type x_server_authorization_hmac_sha256: str
        :param post_pim_v1_category_products_set_request:
        :type post_pim_v1_category_products_set_request: PostPimV1CategoryProductsSetRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._post_pim_v1_category_products_set_serialize(
            x_external_integrator_id=x_external_integrator_id,
            x_server_authorization_hmac_sha256=x_server_authorization_hmac_sha256,
            post_pim_v1_category_products_set_request=post_pim_v1_category_products_set_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "InlineObject1",
            '400': None,
            '401': None,
            '403': None,
            '429': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _post_pim_v1_category_products_set_serialize(
        self,
        x_external_integrator_id,
        x_server_authorization_hmac_sha256,
        post_pim_v1_category_products_set_request,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        # process the header parameters
        if x_external_integrator_id is not None:
            _header_params['x-external-integrator-id'] = x_external_integrator_id
        if x_server_authorization_hmac_sha256 is not None:
            _header_params['x-server-authorization-hmac-sha256'] = x_server_authorization_hmac_sha256
        # process the form parameters
        # process the body parameter
        if post_pim_v1_category_products_set_request is not None:
            _body_params = post_pim_v1_category_products_set_request


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/pim/v1/category/products/set',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def post_pim_v1_category_rearrange(
        self,
        x_external_integrator_id: Annotated[StrictStr, Field(description="Integration ID provided by Bolt Food. It will be unique across all providers. ")],
        x_server_authorization_hmac_sha256: Annotated[StrictStr, Field(description="Signature of the raw payload outputted in base64, computed with sha256 algorithm and a secret key that you will receive from Bolt Food. ")],
        post_pim_v1_category_rearrange_request: Optional[PostPimV1CategoryRearrangeRequest] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> InlineObject1:
        """Rearrange categories

        Rearranges existing subcategories of a specific parent category according to the order of `ordered_category_external_ids` in the request _(you can enable this feature by contacting the Bolt Food support)_.  If categories in the request do not exist or belong to a different parent, a `CATEGORY_NOT_FOUND` (code: 40038) error will be returned and changes will be discarded.  **NB**. Rearranging the category tree does not automatically update  the menu in the Bolt Food app. To do so, the menu publishing flow needs to be invoked. See  [Assortment and Menu Publishing Flow](#tag/Doc-Warehouse-and-PIM-integration/Assortment-and-menu-publishing-flow). 

        :param x_external_integrator_id: Integration ID provided by Bolt Food. It will be unique across all providers.  (required)
        :type x_external_integrator_id: str
        :param x_server_authorization_hmac_sha256: Signature of the raw payload outputted in base64, computed with sha256 algorithm and a secret key that you will receive from Bolt Food.  (required)
        :type x_server_authorization_hmac_sha256: str
        :param post_pim_v1_category_rearrange_request:
        :type post_pim_v1_category_rearrange_request: PostPimV1CategoryRearrangeRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._post_pim_v1_category_rearrange_serialize(
            x_external_integrator_id=x_external_integrator_id,
            x_server_authorization_hmac_sha256=x_server_authorization_hmac_sha256,
            post_pim_v1_category_rearrange_request=post_pim_v1_category_rearrange_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "InlineObject1",
            '400': None,
            '401': None,
            '403': None,
            '429': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def post_pim_v1_category_rearrange_with_http_info(
        self,
        x_external_integrator_id: Annotated[StrictStr, Field(description="Integration ID provided by Bolt Food. It will be unique across all providers. ")],
        x_server_authorization_hmac_sha256: Annotated[StrictStr, Field(description="Signature of the raw payload outputted in base64, computed with sha256 algorithm and a secret key that you will receive from Bolt Food. ")],
        post_pim_v1_category_rearrange_request: Optional[PostPimV1CategoryRearrangeRequest] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[InlineObject1]:
        """Rearrange categories

        Rearranges existing subcategories of a specific parent category according to the order of `ordered_category_external_ids` in the request _(you can enable this feature by contacting the Bolt Food support)_.  If categories in the request do not exist or belong to a different parent, a `CATEGORY_NOT_FOUND` (code: 40038) error will be returned and changes will be discarded.  **NB**. Rearranging the category tree does not automatically update  the menu in the Bolt Food app. To do so, the menu publishing flow needs to be invoked. See  [Assortment and Menu Publishing Flow](#tag/Doc-Warehouse-and-PIM-integration/Assortment-and-menu-publishing-flow). 

        :param x_external_integrator_id: Integration ID provided by Bolt Food. It will be unique across all providers.  (required)
        :type x_external_integrator_id: str
        :param x_server_authorization_hmac_sha256: Signature of the raw payload outputted in base64, computed with sha256 algorithm and a secret key that you will receive from Bolt Food.  (required)
        :type x_server_authorization_hmac_sha256: str
        :param post_pim_v1_category_rearrange_request:
        :type post_pim_v1_category_rearrange_request: PostPimV1CategoryRearrangeRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._post_pim_v1_category_rearrange_serialize(
            x_external_integrator_id=x_external_integrator_id,
            x_server_authorization_hmac_sha256=x_server_authorization_hmac_sha256,
            post_pim_v1_category_rearrange_request=post_pim_v1_category_rearrange_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "InlineObject1",
            '400': None,
            '401': None,
            '403': None,
            '429': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def post_pim_v1_category_rearrange_without_preload_content(
        self,
        x_external_integrator_id: Annotated[StrictStr, Field(description="Integration ID provided by Bolt Food. It will be unique across all providers. ")],
        x_server_authorization_hmac_sha256: Annotated[StrictStr, Field(description="Signature of the raw payload outputted in base64, computed with sha256 algorithm and a secret key that you will receive from Bolt Food. ")],
        post_pim_v1_category_rearrange_request: Optional[PostPimV1CategoryRearrangeRequest] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Rearrange categories

        Rearranges existing subcategories of a specific parent category according to the order of `ordered_category_external_ids` in the request _(you can enable this feature by contacting the Bolt Food support)_.  If categories in the request do not exist or belong to a different parent, a `CATEGORY_NOT_FOUND` (code: 40038) error will be returned and changes will be discarded.  **NB**. Rearranging the category tree does not automatically update  the menu in the Bolt Food app. To do so, the menu publishing flow needs to be invoked. See  [Assortment and Menu Publishing Flow](#tag/Doc-Warehouse-and-PIM-integration/Assortment-and-menu-publishing-flow). 

        :param x_external_integrator_id: Integration ID provided by Bolt Food. It will be unique across all providers.  (required)
        :type x_external_integrator_id: str
        :param x_server_authorization_hmac_sha256: Signature of the raw payload outputted in base64, computed with sha256 algorithm and a secret key that you will receive from Bolt Food.  (required)
        :type x_server_authorization_hmac_sha256: str
        :param post_pim_v1_category_rearrange_request:
        :type post_pim_v1_category_rearrange_request: PostPimV1CategoryRearrangeRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._post_pim_v1_category_rearrange_serialize(
            x_external_integrator_id=x_external_integrator_id,
            x_server_authorization_hmac_sha256=x_server_authorization_hmac_sha256,
            post_pim_v1_category_rearrange_request=post_pim_v1_category_rearrange_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "InlineObject1",
            '400': None,
            '401': None,
            '403': None,
            '429': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _post_pim_v1_category_rearrange_serialize(
        self,
        x_external_integrator_id,
        x_server_authorization_hmac_sha256,
        post_pim_v1_category_rearrange_request,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        # process the header parameters
        if x_external_integrator_id is not None:
            _header_params['x-external-integrator-id'] = x_external_integrator_id
        if x_server_authorization_hmac_sha256 is not None:
            _header_params['x-server-authorization-hmac-sha256'] = x_server_authorization_hmac_sha256
        # process the form parameters
        # process the body parameter
        if post_pim_v1_category_rearrange_request is not None:
            _body_params = post_pim_v1_category_rearrange_request


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/pim/v1/category/rearrange',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def post_pim_v1_category_tree_get(
        self,
        x_external_integrator_id: Annotated[StrictStr, Field(description="Integration ID provided by Bolt Food. It will be unique across all providers. ")],
        x_server_authorization_hmac_sha256: Annotated[StrictStr, Field(description="Signature of the raw payload outputted in base64, computed with sha256 algorithm and a secret key that you will receive from Bolt Food. ")],
        post_pim_v1_products_import_status_retrieve_request: Optional[PostPimV1ProductsImportStatusRetrieveRequest] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> PostPimV1CategoryTreeGet200Response:
        """Retrieve category tree

        Returns the list of top level categories, each with its own subcategories

        :param x_external_integrator_id: Integration ID provided by Bolt Food. It will be unique across all providers.  (required)
        :type x_external_integrator_id: str
        :param x_server_authorization_hmac_sha256: Signature of the raw payload outputted in base64, computed with sha256 algorithm and a secret key that you will receive from Bolt Food.  (required)
        :type x_server_authorization_hmac_sha256: str
        :param post_pim_v1_products_import_status_retrieve_request:
        :type post_pim_v1_products_import_status_retrieve_request: PostPimV1ProductsImportStatusRetrieveRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._post_pim_v1_category_tree_get_serialize(
            x_external_integrator_id=x_external_integrator_id,
            x_server_authorization_hmac_sha256=x_server_authorization_hmac_sha256,
            post_pim_v1_products_import_status_retrieve_request=post_pim_v1_products_import_status_retrieve_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "PostPimV1CategoryTreeGet200Response",
            '400': None,
            '401': None,
            '403': None,
            '429': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def post_pim_v1_category_tree_get_with_http_info(
        self,
        x_external_integrator_id: Annotated[StrictStr, Field(description="Integration ID provided by Bolt Food. It will be unique across all providers. ")],
        x_server_authorization_hmac_sha256: Annotated[StrictStr, Field(description="Signature of the raw payload outputted in base64, computed with sha256 algorithm and a secret key that you will receive from Bolt Food. ")],
        post_pim_v1_products_import_status_retrieve_request: Optional[PostPimV1ProductsImportStatusRetrieveRequest] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[PostPimV1CategoryTreeGet200Response]:
        """Retrieve category tree

        Returns the list of top level categories, each with its own subcategories

        :param x_external_integrator_id: Integration ID provided by Bolt Food. It will be unique across all providers.  (required)
        :type x_external_integrator_id: str
        :param x_server_authorization_hmac_sha256: Signature of the raw payload outputted in base64, computed with sha256 algorithm and a secret key that you will receive from Bolt Food.  (required)
        :type x_server_authorization_hmac_sha256: str
        :param post_pim_v1_products_import_status_retrieve_request:
        :type post_pim_v1_products_import_status_retrieve_request: PostPimV1ProductsImportStatusRetrieveRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._post_pim_v1_category_tree_get_serialize(
            x_external_integrator_id=x_external_integrator_id,
            x_server_authorization_hmac_sha256=x_server_authorization_hmac_sha256,
            post_pim_v1_products_import_status_retrieve_request=post_pim_v1_products_import_status_retrieve_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "PostPimV1CategoryTreeGet200Response",
            '400': None,
            '401': None,
            '403': None,
            '429': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def post_pim_v1_category_tree_get_without_preload_content(
        self,
        x_external_integrator_id: Annotated[StrictStr, Field(description="Integration ID provided by Bolt Food. It will be unique across all providers. ")],
        x_server_authorization_hmac_sha256: Annotated[StrictStr, Field(description="Signature of the raw payload outputted in base64, computed with sha256 algorithm and a secret key that you will receive from Bolt Food. ")],
        post_pim_v1_products_import_status_retrieve_request: Optional[PostPimV1ProductsImportStatusRetrieveRequest] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Retrieve category tree

        Returns the list of top level categories, each with its own subcategories

        :param x_external_integrator_id: Integration ID provided by Bolt Food. It will be unique across all providers.  (required)
        :type x_external_integrator_id: str
        :param x_server_authorization_hmac_sha256: Signature of the raw payload outputted in base64, computed with sha256 algorithm and a secret key that you will receive from Bolt Food.  (required)
        :type x_server_authorization_hmac_sha256: str
        :param post_pim_v1_products_import_status_retrieve_request:
        :type post_pim_v1_products_import_status_retrieve_request: PostPimV1ProductsImportStatusRetrieveRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._post_pim_v1_category_tree_get_serialize(
            x_external_integrator_id=x_external_integrator_id,
            x_server_authorization_hmac_sha256=x_server_authorization_hmac_sha256,
            post_pim_v1_products_import_status_retrieve_request=post_pim_v1_products_import_status_retrieve_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "PostPimV1CategoryTreeGet200Response",
            '400': None,
            '401': None,
            '403': None,
            '429': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _post_pim_v1_category_tree_get_serialize(
        self,
        x_external_integrator_id,
        x_server_authorization_hmac_sha256,
        post_pim_v1_products_import_status_retrieve_request,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        # process the header parameters
        if x_external_integrator_id is not None:
            _header_params['x-external-integrator-id'] = x_external_integrator_id
        if x_server_authorization_hmac_sha256 is not None:
            _header_params['x-server-authorization-hmac-sha256'] = x_server_authorization_hmac_sha256
        # process the form parameters
        # process the body parameter
        if post_pim_v1_products_import_status_retrieve_request is not None:
            _body_params = post_pim_v1_products_import_status_retrieve_request


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/pim/v1/categoryTree/get',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def post_pim_v1_category_tree_set(
        self,
        x_external_integrator_id: Annotated[StrictStr, Field(description="Integration ID provided by Bolt Food. It will be unique across all providers. ")],
        x_server_authorization_hmac_sha256: Annotated[StrictStr, Field(description="Signature of the raw payload outputted in base64, computed with sha256 algorithm and a secret key that you will receive from Bolt Food. ")],
        post_pim_v1_category_tree_set_request: Optional[PostPimV1CategoryTreeSetRequest] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> PostPimV1CategoryTreeGet200Response:
        """Set category tree

        Sets/overwrites the category tree for the region, this can be used to add, remove, update, or rearrange categories by supplying the full tree in its new state.  All subcategories are expected to exclusively belong to a single top-level category and may not be duplicated within the category tree, this means that each node in the tree **MUST** have a unique external_id if provided in the request, it's recommended to use some composite format for provided subcategory external_ids that ensures uniqueness globally within the entire category tree such as `<category>:<subcategory>`.  `external_id` is mandatory for category requests that have the property `external_provider_ids` set. If the `external_id` is missing for such cases, a `STORE_CATEGORY_EXTERNAL_ID_REQUIRED` (code: 4200007) error will be returned.  Use `render_in` property of the top-level categories to specify the section ID in the layout where the category should be rendered. See [Sections layout](#tag/PIM-integration:-Sections-layout) for more details.  **NB**. Setting a category tree does not automatically update  the menu in the Bolt Food app. To do so, the menu publishing flow needs to be invoked. See  [Assortment and Menu Publishing Flow](#tag/Doc-Warehouse-and-PIM-integration/Assortment-and-menu-publishing-flow). 

        :param x_external_integrator_id: Integration ID provided by Bolt Food. It will be unique across all providers.  (required)
        :type x_external_integrator_id: str
        :param x_server_authorization_hmac_sha256: Signature of the raw payload outputted in base64, computed with sha256 algorithm and a secret key that you will receive from Bolt Food.  (required)
        :type x_server_authorization_hmac_sha256: str
        :param post_pim_v1_category_tree_set_request:
        :type post_pim_v1_category_tree_set_request: PostPimV1CategoryTreeSetRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._post_pim_v1_category_tree_set_serialize(
            x_external_integrator_id=x_external_integrator_id,
            x_server_authorization_hmac_sha256=x_server_authorization_hmac_sha256,
            post_pim_v1_category_tree_set_request=post_pim_v1_category_tree_set_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "PostPimV1CategoryTreeGet200Response",
            '400': None,
            '401': None,
            '403': None,
            '429': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def post_pim_v1_category_tree_set_with_http_info(
        self,
        x_external_integrator_id: Annotated[StrictStr, Field(description="Integration ID provided by Bolt Food. It will be unique across all providers. ")],
        x_server_authorization_hmac_sha256: Annotated[StrictStr, Field(description="Signature of the raw payload outputted in base64, computed with sha256 algorithm and a secret key that you will receive from Bolt Food. ")],
        post_pim_v1_category_tree_set_request: Optional[PostPimV1CategoryTreeSetRequest] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[PostPimV1CategoryTreeGet200Response]:
        """Set category tree

        Sets/overwrites the category tree for the region, this can be used to add, remove, update, or rearrange categories by supplying the full tree in its new state.  All subcategories are expected to exclusively belong to a single top-level category and may not be duplicated within the category tree, this means that each node in the tree **MUST** have a unique external_id if provided in the request, it's recommended to use some composite format for provided subcategory external_ids that ensures uniqueness globally within the entire category tree such as `<category>:<subcategory>`.  `external_id` is mandatory for category requests that have the property `external_provider_ids` set. If the `external_id` is missing for such cases, a `STORE_CATEGORY_EXTERNAL_ID_REQUIRED` (code: 4200007) error will be returned.  Use `render_in` property of the top-level categories to specify the section ID in the layout where the category should be rendered. See [Sections layout](#tag/PIM-integration:-Sections-layout) for more details.  **NB**. Setting a category tree does not automatically update  the menu in the Bolt Food app. To do so, the menu publishing flow needs to be invoked. See  [Assortment and Menu Publishing Flow](#tag/Doc-Warehouse-and-PIM-integration/Assortment-and-menu-publishing-flow). 

        :param x_external_integrator_id: Integration ID provided by Bolt Food. It will be unique across all providers.  (required)
        :type x_external_integrator_id: str
        :param x_server_authorization_hmac_sha256: Signature of the raw payload outputted in base64, computed with sha256 algorithm and a secret key that you will receive from Bolt Food.  (required)
        :type x_server_authorization_hmac_sha256: str
        :param post_pim_v1_category_tree_set_request:
        :type post_pim_v1_category_tree_set_request: PostPimV1CategoryTreeSetRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._post_pim_v1_category_tree_set_serialize(
            x_external_integrator_id=x_external_integrator_id,
            x_server_authorization_hmac_sha256=x_server_authorization_hmac_sha256,
            post_pim_v1_category_tree_set_request=post_pim_v1_category_tree_set_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "PostPimV1CategoryTreeGet200Response",
            '400': None,
            '401': None,
            '403': None,
            '429': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def post_pim_v1_category_tree_set_without_preload_content(
        self,
        x_external_integrator_id: Annotated[StrictStr, Field(description="Integration ID provided by Bolt Food. It will be unique across all providers. ")],
        x_server_authorization_hmac_sha256: Annotated[StrictStr, Field(description="Signature of the raw payload outputted in base64, computed with sha256 algorithm and a secret key that you will receive from Bolt Food. ")],
        post_pim_v1_category_tree_set_request: Optional[PostPimV1CategoryTreeSetRequest] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Set category tree

        Sets/overwrites the category tree for the region, this can be used to add, remove, update, or rearrange categories by supplying the full tree in its new state.  All subcategories are expected to exclusively belong to a single top-level category and may not be duplicated within the category tree, this means that each node in the tree **MUST** have a unique external_id if provided in the request, it's recommended to use some composite format for provided subcategory external_ids that ensures uniqueness globally within the entire category tree such as `<category>:<subcategory>`.  `external_id` is mandatory for category requests that have the property `external_provider_ids` set. If the `external_id` is missing for such cases, a `STORE_CATEGORY_EXTERNAL_ID_REQUIRED` (code: 4200007) error will be returned.  Use `render_in` property of the top-level categories to specify the section ID in the layout where the category should be rendered. See [Sections layout](#tag/PIM-integration:-Sections-layout) for more details.  **NB**. Setting a category tree does not automatically update  the menu in the Bolt Food app. To do so, the menu publishing flow needs to be invoked. See  [Assortment and Menu Publishing Flow](#tag/Doc-Warehouse-and-PIM-integration/Assortment-and-menu-publishing-flow). 

        :param x_external_integrator_id: Integration ID provided by Bolt Food. It will be unique across all providers.  (required)
        :type x_external_integrator_id: str
        :param x_server_authorization_hmac_sha256: Signature of the raw payload outputted in base64, computed with sha256 algorithm and a secret key that you will receive from Bolt Food.  (required)
        :type x_server_authorization_hmac_sha256: str
        :param post_pim_v1_category_tree_set_request:
        :type post_pim_v1_category_tree_set_request: PostPimV1CategoryTreeSetRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._post_pim_v1_category_tree_set_serialize(
            x_external_integrator_id=x_external_integrator_id,
            x_server_authorization_hmac_sha256=x_server_authorization_hmac_sha256,
            post_pim_v1_category_tree_set_request=post_pim_v1_category_tree_set_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "PostPimV1CategoryTreeGet200Response",
            '400': None,
            '401': None,
            '403': None,
            '429': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _post_pim_v1_category_tree_set_serialize(
        self,
        x_external_integrator_id,
        x_server_authorization_hmac_sha256,
        post_pim_v1_category_tree_set_request,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        # process the header parameters
        if x_external_integrator_id is not None:
            _header_params['x-external-integrator-id'] = x_external_integrator_id
        if x_server_authorization_hmac_sha256 is not None:
            _header_params['x-server-authorization-hmac-sha256'] = x_server_authorization_hmac_sha256
        # process the form parameters
        # process the body parameter
        if post_pim_v1_category_tree_set_request is not None:
            _body_params = post_pim_v1_category_tree_set_request


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/pim/v1/categoryTree/set',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


