# coding: utf-8

"""
    BoltStoresAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictStr
from typing import Optional
from typing_extensions import Annotated
from openapi_client.models.post_pim_v1_layout_set_request import PostPimV1LayoutSetRequest
from openapi_client.models.successful_operation_result import SuccessfulOperationResult

from openapi_client.api_client import ApiClient, RequestSerialized
from openapi_client.api_response import ApiResponse
from openapi_client.rest import RESTResponseType


class PIMIntegrationSectionsLayoutApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def post_pim_v1_layout_set(
        self,
        x_external_integrator_id: Annotated[StrictStr, Field(description="Integration ID provided by Bolt Food. It will be unique across all providers. ")],
        x_server_authorization_hmac_sha256: Annotated[StrictStr, Field(description="Signature of the raw payload outputted in base64, computed with sha256 algorithm and a secret key that you will receive from Bolt Food. ")],
        post_pim_v1_layout_set_request: Optional[PostPimV1LayoutSetRequest] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> SuccessfulOperationResult:
        """Set sections layout

        Sections allow grouping categories and affect the way they are displayed in the Bolt Food app. This feature works together with categories. First, this endpoint should be used to set up sections, and then the [Categories and Ordering](#tag/PIM-integration:-Categories-and-Ordering/operation/post-pimV1CategoryTreeSet) endpoint should be used to set up categories with references to sections.  The order of sections in the layout is determined by the `position` field in the request. The lower the number, the higher the section in the layout. If it happens that a category references a section that no longer exists, such category will be rendered in the end of all sections in the Bolt Food app.  **NB**. Unlike categories changes, sections layout changes are visible instantly. Hence, if category references to sections have to be updated as well, a menu publishing has to be done. See [Assortment and Menu Publishing Flow](#tag/Doc-Warehouse-and-PIM-integration/Assortment-and-menu-publishing-flow). 

        :param x_external_integrator_id: Integration ID provided by Bolt Food. It will be unique across all providers.  (required)
        :type x_external_integrator_id: str
        :param x_server_authorization_hmac_sha256: Signature of the raw payload outputted in base64, computed with sha256 algorithm and a secret key that you will receive from Bolt Food.  (required)
        :type x_server_authorization_hmac_sha256: str
        :param post_pim_v1_layout_set_request:
        :type post_pim_v1_layout_set_request: PostPimV1LayoutSetRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._post_pim_v1_layout_set_serialize(
            x_external_integrator_id=x_external_integrator_id,
            x_server_authorization_hmac_sha256=x_server_authorization_hmac_sha256,
            post_pim_v1_layout_set_request=post_pim_v1_layout_set_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "SuccessfulOperationResult",
            '400': "PostPimV1LayoutSet400Response",
            '401': None,
            '403': None,
            '429': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def post_pim_v1_layout_set_with_http_info(
        self,
        x_external_integrator_id: Annotated[StrictStr, Field(description="Integration ID provided by Bolt Food. It will be unique across all providers. ")],
        x_server_authorization_hmac_sha256: Annotated[StrictStr, Field(description="Signature of the raw payload outputted in base64, computed with sha256 algorithm and a secret key that you will receive from Bolt Food. ")],
        post_pim_v1_layout_set_request: Optional[PostPimV1LayoutSetRequest] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[SuccessfulOperationResult]:
        """Set sections layout

        Sections allow grouping categories and affect the way they are displayed in the Bolt Food app. This feature works together with categories. First, this endpoint should be used to set up sections, and then the [Categories and Ordering](#tag/PIM-integration:-Categories-and-Ordering/operation/post-pimV1CategoryTreeSet) endpoint should be used to set up categories with references to sections.  The order of sections in the layout is determined by the `position` field in the request. The lower the number, the higher the section in the layout. If it happens that a category references a section that no longer exists, such category will be rendered in the end of all sections in the Bolt Food app.  **NB**. Unlike categories changes, sections layout changes are visible instantly. Hence, if category references to sections have to be updated as well, a menu publishing has to be done. See [Assortment and Menu Publishing Flow](#tag/Doc-Warehouse-and-PIM-integration/Assortment-and-menu-publishing-flow). 

        :param x_external_integrator_id: Integration ID provided by Bolt Food. It will be unique across all providers.  (required)
        :type x_external_integrator_id: str
        :param x_server_authorization_hmac_sha256: Signature of the raw payload outputted in base64, computed with sha256 algorithm and a secret key that you will receive from Bolt Food.  (required)
        :type x_server_authorization_hmac_sha256: str
        :param post_pim_v1_layout_set_request:
        :type post_pim_v1_layout_set_request: PostPimV1LayoutSetRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._post_pim_v1_layout_set_serialize(
            x_external_integrator_id=x_external_integrator_id,
            x_server_authorization_hmac_sha256=x_server_authorization_hmac_sha256,
            post_pim_v1_layout_set_request=post_pim_v1_layout_set_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "SuccessfulOperationResult",
            '400': "PostPimV1LayoutSet400Response",
            '401': None,
            '403': None,
            '429': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def post_pim_v1_layout_set_without_preload_content(
        self,
        x_external_integrator_id: Annotated[StrictStr, Field(description="Integration ID provided by Bolt Food. It will be unique across all providers. ")],
        x_server_authorization_hmac_sha256: Annotated[StrictStr, Field(description="Signature of the raw payload outputted in base64, computed with sha256 algorithm and a secret key that you will receive from Bolt Food. ")],
        post_pim_v1_layout_set_request: Optional[PostPimV1LayoutSetRequest] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Set sections layout

        Sections allow grouping categories and affect the way they are displayed in the Bolt Food app. This feature works together with categories. First, this endpoint should be used to set up sections, and then the [Categories and Ordering](#tag/PIM-integration:-Categories-and-Ordering/operation/post-pimV1CategoryTreeSet) endpoint should be used to set up categories with references to sections.  The order of sections in the layout is determined by the `position` field in the request. The lower the number, the higher the section in the layout. If it happens that a category references a section that no longer exists, such category will be rendered in the end of all sections in the Bolt Food app.  **NB**. Unlike categories changes, sections layout changes are visible instantly. Hence, if category references to sections have to be updated as well, a menu publishing has to be done. See [Assortment and Menu Publishing Flow](#tag/Doc-Warehouse-and-PIM-integration/Assortment-and-menu-publishing-flow). 

        :param x_external_integrator_id: Integration ID provided by Bolt Food. It will be unique across all providers.  (required)
        :type x_external_integrator_id: str
        :param x_server_authorization_hmac_sha256: Signature of the raw payload outputted in base64, computed with sha256 algorithm and a secret key that you will receive from Bolt Food.  (required)
        :type x_server_authorization_hmac_sha256: str
        :param post_pim_v1_layout_set_request:
        :type post_pim_v1_layout_set_request: PostPimV1LayoutSetRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._post_pim_v1_layout_set_serialize(
            x_external_integrator_id=x_external_integrator_id,
            x_server_authorization_hmac_sha256=x_server_authorization_hmac_sha256,
            post_pim_v1_layout_set_request=post_pim_v1_layout_set_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "SuccessfulOperationResult",
            '400': "PostPimV1LayoutSet400Response",
            '401': None,
            '403': None,
            '429': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _post_pim_v1_layout_set_serialize(
        self,
        x_external_integrator_id,
        x_server_authorization_hmac_sha256,
        post_pim_v1_layout_set_request,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        # process the header parameters
        if x_external_integrator_id is not None:
            _header_params['x-external-integrator-id'] = x_external_integrator_id
        if x_server_authorization_hmac_sha256 is not None:
            _header_params['x-server-authorization-hmac-sha256'] = x_server_authorization_hmac_sha256
        # process the form parameters
        # process the body parameter
        if post_pim_v1_layout_set_request is not None:
            _body_params = post_pim_v1_layout_set_request


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/pim/v1/layout/set',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


