# coding: utf-8

"""
    BoltStoresAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictStr
from typing import Optional
from typing_extensions import Annotated
from openapi_client.models.post_start_accepting_orders_request import PostStartAcceptingOrdersRequest
from openapi_client.models.post_update_provider_schedule_request import PostUpdateProviderScheduleRequest

from openapi_client.api_client import ApiClient, RequestSerialized
from openapi_client.api_response import ApiResponse
from openapi_client.rest import RESTResponseType


class ProviderIntegrationApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def post_start_accepting_orders(
        self,
        x_external_integrator_id: Annotated[StrictStr, Field(description="Integration ID provided by Bolt Food. It will be unique across all providers. ")],
        x_server_authorization_hmac_sha256: Annotated[StrictStr, Field(description="Signature of the raw payload outputted in base64, computed with sha256 algorithm and a secret key that you will receive from Bolt Food. ")],
        post_start_accepting_orders_request: Optional[PostStartAcceptingOrdersRequest] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> None:
        """Start accepting orders

        The integrator should call this endpoint in order to start accepting new orders. 

        :param x_external_integrator_id: Integration ID provided by Bolt Food. It will be unique across all providers.  (required)
        :type x_external_integrator_id: str
        :param x_server_authorization_hmac_sha256: Signature of the raw payload outputted in base64, computed with sha256 algorithm and a secret key that you will receive from Bolt Food.  (required)
        :type x_server_authorization_hmac_sha256: str
        :param post_start_accepting_orders_request:
        :type post_start_accepting_orders_request: PostStartAcceptingOrdersRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._post_start_accepting_orders_serialize(
            x_external_integrator_id=x_external_integrator_id,
            x_server_authorization_hmac_sha256=x_server_authorization_hmac_sha256,
            post_start_accepting_orders_request=post_start_accepting_orders_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': None,
            '304': None,
            '400': None,
            '401': None,
            '403': None,
            '404': None,
            '429': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def post_start_accepting_orders_with_http_info(
        self,
        x_external_integrator_id: Annotated[StrictStr, Field(description="Integration ID provided by Bolt Food. It will be unique across all providers. ")],
        x_server_authorization_hmac_sha256: Annotated[StrictStr, Field(description="Signature of the raw payload outputted in base64, computed with sha256 algorithm and a secret key that you will receive from Bolt Food. ")],
        post_start_accepting_orders_request: Optional[PostStartAcceptingOrdersRequest] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[None]:
        """Start accepting orders

        The integrator should call this endpoint in order to start accepting new orders. 

        :param x_external_integrator_id: Integration ID provided by Bolt Food. It will be unique across all providers.  (required)
        :type x_external_integrator_id: str
        :param x_server_authorization_hmac_sha256: Signature of the raw payload outputted in base64, computed with sha256 algorithm and a secret key that you will receive from Bolt Food.  (required)
        :type x_server_authorization_hmac_sha256: str
        :param post_start_accepting_orders_request:
        :type post_start_accepting_orders_request: PostStartAcceptingOrdersRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._post_start_accepting_orders_serialize(
            x_external_integrator_id=x_external_integrator_id,
            x_server_authorization_hmac_sha256=x_server_authorization_hmac_sha256,
            post_start_accepting_orders_request=post_start_accepting_orders_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': None,
            '304': None,
            '400': None,
            '401': None,
            '403': None,
            '404': None,
            '429': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def post_start_accepting_orders_without_preload_content(
        self,
        x_external_integrator_id: Annotated[StrictStr, Field(description="Integration ID provided by Bolt Food. It will be unique across all providers. ")],
        x_server_authorization_hmac_sha256: Annotated[StrictStr, Field(description="Signature of the raw payload outputted in base64, computed with sha256 algorithm and a secret key that you will receive from Bolt Food. ")],
        post_start_accepting_orders_request: Optional[PostStartAcceptingOrdersRequest] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Start accepting orders

        The integrator should call this endpoint in order to start accepting new orders. 

        :param x_external_integrator_id: Integration ID provided by Bolt Food. It will be unique across all providers.  (required)
        :type x_external_integrator_id: str
        :param x_server_authorization_hmac_sha256: Signature of the raw payload outputted in base64, computed with sha256 algorithm and a secret key that you will receive from Bolt Food.  (required)
        :type x_server_authorization_hmac_sha256: str
        :param post_start_accepting_orders_request:
        :type post_start_accepting_orders_request: PostStartAcceptingOrdersRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._post_start_accepting_orders_serialize(
            x_external_integrator_id=x_external_integrator_id,
            x_server_authorization_hmac_sha256=x_server_authorization_hmac_sha256,
            post_start_accepting_orders_request=post_start_accepting_orders_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': None,
            '304': None,
            '400': None,
            '401': None,
            '403': None,
            '404': None,
            '429': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _post_start_accepting_orders_serialize(
        self,
        x_external_integrator_id,
        x_server_authorization_hmac_sha256,
        post_start_accepting_orders_request,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        # process the header parameters
        if x_external_integrator_id is not None:
            _header_params['x-external-integrator-id'] = x_external_integrator_id
        if x_server_authorization_hmac_sha256 is not None:
            _header_params['x-server-authorization-hmac-sha256'] = x_server_authorization_hmac_sha256
        # process the form parameters
        # process the body parameter
        if post_start_accepting_orders_request is not None:
            _body_params = post_start_accepting_orders_request



        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/genericClient/startAcceptingOrders',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def post_update_provider_schedule(
        self,
        x_external_integrator_id: Annotated[StrictStr, Field(description="Integration ID provided by Bolt Food. It will be unique across all providers. ")],
        x_server_authorization_hmac_sha256: Annotated[StrictStr, Field(description="Signature of the raw payload outputted in base64, computed with sha256 algorithm and a secret key that you will receive from Bolt Food. ")],
        post_update_provider_schedule_request: Optional[PostUpdateProviderScheduleRequest] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> None:
        """Update provider schedule

        Endpoint used to set provider working hours.  In case working hours are 18:00 PM -> 1:00 AM, then it needs to be defined in 2 different days: 18:00-23:59 and 00:00-01:00, see example-2  *Timezone:* The working hours provided need to be relative to the local city timezone. 

        :param x_external_integrator_id: Integration ID provided by Bolt Food. It will be unique across all providers.  (required)
        :type x_external_integrator_id: str
        :param x_server_authorization_hmac_sha256: Signature of the raw payload outputted in base64, computed with sha256 algorithm and a secret key that you will receive from Bolt Food.  (required)
        :type x_server_authorization_hmac_sha256: str
        :param post_update_provider_schedule_request: 
        :type post_update_provider_schedule_request: PostUpdateProviderScheduleRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._post_update_provider_schedule_serialize(
            x_external_integrator_id=x_external_integrator_id,
            x_server_authorization_hmac_sha256=x_server_authorization_hmac_sha256,
            post_update_provider_schedule_request=post_update_provider_schedule_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': None,
            '304': None,
            '400': None,
            '401': None,
            '403': None,
            '404': None,
            '429': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def post_update_provider_schedule_with_http_info(
        self,
        x_external_integrator_id: Annotated[StrictStr, Field(description="Integration ID provided by Bolt Food. It will be unique across all providers. ")],
        x_server_authorization_hmac_sha256: Annotated[StrictStr, Field(description="Signature of the raw payload outputted in base64, computed with sha256 algorithm and a secret key that you will receive from Bolt Food. ")],
        post_update_provider_schedule_request: Optional[PostUpdateProviderScheduleRequest] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[None]:
        """Update provider schedule

        Endpoint used to set provider working hours.  In case working hours are 18:00 PM -> 1:00 AM, then it needs to be defined in 2 different days: 18:00-23:59 and 00:00-01:00, see example-2  *Timezone:* The working hours provided need to be relative to the local city timezone. 

        :param x_external_integrator_id: Integration ID provided by Bolt Food. It will be unique across all providers.  (required)
        :type x_external_integrator_id: str
        :param x_server_authorization_hmac_sha256: Signature of the raw payload outputted in base64, computed with sha256 algorithm and a secret key that you will receive from Bolt Food.  (required)
        :type x_server_authorization_hmac_sha256: str
        :param post_update_provider_schedule_request: 
        :type post_update_provider_schedule_request: PostUpdateProviderScheduleRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._post_update_provider_schedule_serialize(
            x_external_integrator_id=x_external_integrator_id,
            x_server_authorization_hmac_sha256=x_server_authorization_hmac_sha256,
            post_update_provider_schedule_request=post_update_provider_schedule_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': None,
            '304': None,
            '400': None,
            '401': None,
            '403': None,
            '404': None,
            '429': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def post_update_provider_schedule_without_preload_content(
        self,
        x_external_integrator_id: Annotated[StrictStr, Field(description="Integration ID provided by Bolt Food. It will be unique across all providers. ")],
        x_server_authorization_hmac_sha256: Annotated[StrictStr, Field(description="Signature of the raw payload outputted in base64, computed with sha256 algorithm and a secret key that you will receive from Bolt Food. ")],
        post_update_provider_schedule_request: Optional[PostUpdateProviderScheduleRequest] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Update provider schedule

        Endpoint used to set provider working hours.  In case working hours are 18:00 PM -> 1:00 AM, then it needs to be defined in 2 different days: 18:00-23:59 and 00:00-01:00, see example-2  *Timezone:* The working hours provided need to be relative to the local city timezone. 

        :param x_external_integrator_id: Integration ID provided by Bolt Food. It will be unique across all providers.  (required)
        :type x_external_integrator_id: str
        :param x_server_authorization_hmac_sha256: Signature of the raw payload outputted in base64, computed with sha256 algorithm and a secret key that you will receive from Bolt Food.  (required)
        :type x_server_authorization_hmac_sha256: str
        :param post_update_provider_schedule_request: 
        :type post_update_provider_schedule_request: PostUpdateProviderScheduleRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._post_update_provider_schedule_serialize(
            x_external_integrator_id=x_external_integrator_id,
            x_server_authorization_hmac_sha256=x_server_authorization_hmac_sha256,
            post_update_provider_schedule_request=post_update_provider_schedule_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': None,
            '304': None,
            '400': None,
            '401': None,
            '403': None,
            '404': None,
            '429': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _post_update_provider_schedule_serialize(
        self,
        x_external_integrator_id,
        x_server_authorization_hmac_sha256,
        post_update_provider_schedule_request,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        # process the header parameters
        if x_external_integrator_id is not None:
            _header_params['x-external-integrator-id'] = x_external_integrator_id
        if x_server_authorization_hmac_sha256 is not None:
            _header_params['x-server-authorization-hmac-sha256'] = x_server_authorization_hmac_sha256
        # process the form parameters
        # process the body parameter
        if post_update_provider_schedule_request is not None:
            _body_params = post_update_provider_schedule_request



        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/genericClient/updateProviderSchedule',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def post_user(
        self,
        x_external_integrator_id: Annotated[StrictStr, Field(description="Integration ID provided by Bolt Food. It will be unique across all providers. ")],
        x_server_authorization_hmac_sha256: Annotated[StrictStr, Field(description="Signature of the raw payload outputted in base64, computed with sha256 algorithm and a secret key that you will receive from Bolt Food. ")],
        post_start_accepting_orders_request: Optional[PostStartAcceptingOrdersRequest] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> None:
        """Pause Orders

        The integrator should call this endpoint when they wish to pause new orders from coming in. 

        :param x_external_integrator_id: Integration ID provided by Bolt Food. It will be unique across all providers.  (required)
        :type x_external_integrator_id: str
        :param x_server_authorization_hmac_sha256: Signature of the raw payload outputted in base64, computed with sha256 algorithm and a secret key that you will receive from Bolt Food.  (required)
        :type x_server_authorization_hmac_sha256: str
        :param post_start_accepting_orders_request: 
        :type post_start_accepting_orders_request: PostStartAcceptingOrdersRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._post_user_serialize(
            x_external_integrator_id=x_external_integrator_id,
            x_server_authorization_hmac_sha256=x_server_authorization_hmac_sha256,
            post_start_accepting_orders_request=post_start_accepting_orders_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': None,
            '304': None,
            '400': None,
            '401': None,
            '403': None,
            '404': None,
            '429': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def post_user_with_http_info(
        self,
        x_external_integrator_id: Annotated[StrictStr, Field(description="Integration ID provided by Bolt Food. It will be unique across all providers. ")],
        x_server_authorization_hmac_sha256: Annotated[StrictStr, Field(description="Signature of the raw payload outputted in base64, computed with sha256 algorithm and a secret key that you will receive from Bolt Food. ")],
        post_start_accepting_orders_request: Optional[PostStartAcceptingOrdersRequest] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[None]:
        """Pause Orders

        The integrator should call this endpoint when they wish to pause new orders from coming in. 

        :param x_external_integrator_id: Integration ID provided by Bolt Food. It will be unique across all providers.  (required)
        :type x_external_integrator_id: str
        :param x_server_authorization_hmac_sha256: Signature of the raw payload outputted in base64, computed with sha256 algorithm and a secret key that you will receive from Bolt Food.  (required)
        :type x_server_authorization_hmac_sha256: str
        :param post_start_accepting_orders_request: 
        :type post_start_accepting_orders_request: PostStartAcceptingOrdersRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._post_user_serialize(
            x_external_integrator_id=x_external_integrator_id,
            x_server_authorization_hmac_sha256=x_server_authorization_hmac_sha256,
            post_start_accepting_orders_request=post_start_accepting_orders_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': None,
            '304': None,
            '400': None,
            '401': None,
            '403': None,
            '404': None,
            '429': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def post_user_without_preload_content(
        self,
        x_external_integrator_id: Annotated[StrictStr, Field(description="Integration ID provided by Bolt Food. It will be unique across all providers. ")],
        x_server_authorization_hmac_sha256: Annotated[StrictStr, Field(description="Signature of the raw payload outputted in base64, computed with sha256 algorithm and a secret key that you will receive from Bolt Food. ")],
        post_start_accepting_orders_request: Optional[PostStartAcceptingOrdersRequest] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Pause Orders

        The integrator should call this endpoint when they wish to pause new orders from coming in. 

        :param x_external_integrator_id: Integration ID provided by Bolt Food. It will be unique across all providers.  (required)
        :type x_external_integrator_id: str
        :param x_server_authorization_hmac_sha256: Signature of the raw payload outputted in base64, computed with sha256 algorithm and a secret key that you will receive from Bolt Food.  (required)
        :type x_server_authorization_hmac_sha256: str
        :param post_start_accepting_orders_request: 
        :type post_start_accepting_orders_request: PostStartAcceptingOrdersRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._post_user_serialize(
            x_external_integrator_id=x_external_integrator_id,
            x_server_authorization_hmac_sha256=x_server_authorization_hmac_sha256,
            post_start_accepting_orders_request=post_start_accepting_orders_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': None,
            '304': None,
            '400': None,
            '401': None,
            '403': None,
            '404': None,
            '429': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _post_user_serialize(
        self,
        x_external_integrator_id,
        x_server_authorization_hmac_sha256,
        post_start_accepting_orders_request,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        # process the header parameters
        if x_external_integrator_id is not None:
            _header_params['x-external-integrator-id'] = x_external_integrator_id
        if x_server_authorization_hmac_sha256 is not None:
            _header_params['x-server-authorization-hmac-sha256'] = x_server_authorization_hmac_sha256
        # process the form parameters
        # process the body parameter
        if post_start_accepting_orders_request is not None:
            _body_params = post_start_accepting_orders_request



        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/genericClient/pauseOrders',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


